#!/bin/bash
### BEGIN INIT INFO
# Provides:          machinestatus
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts the Machine Status Daemon
### END INIT INFO

MODO="$1"
EXECUTANDO=`ps uax | grep machinestatus | grep python | awk -F" " '{ print $2 }'`
case $MODO in
	start)
		if [ "$EXECUTANDO" == "" ]
		then
			echo Iniciando o machinestatus
			sleep 0.5
			/root/machinestatus
		else
			echo machinestatus já está em execução
		fi
		;;
	stop)
		echo Matando o machinestatus
		sleep 0.5
		kill $EXECUTANDO > /dev/null 2> /dev/null
		;;
	restart)
		echo Reiniciando o machinestatus
		/etc/init.d/machinestatus stop
		/etc/init.d/machinestatus start
		;;
	*)
		echo 'Uso: machinestatus {start|stop|restart}'
		;;
esac
